
[build]
  command = ""
  publish = "public"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"
  NETLIFY_NEXT_PLUGIN_SKIP = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"
  enabled = false

[functions]
  node_bundler = "esbuild"
